name: Container-tests by GitHub Action at Testing Farm

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "N"
          echo ${{ github.event.number }}
      - run: |
          echo "PR N"
          echo ${{ github.event.issue_comment.issue.number }}
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.issue_comment.issue.number }}/head"
      - name: Checkout repo 2
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/head"
