name: Container-tests by GitHub Action at Testing Farm

on:
  issue_comment:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github_event_issue_number"
          echo ${{ github.event.issue.number }}
      - run: |
          echo "issue_comment_issue_number"
          echo ${{ github.event.issue_comment.issue.number }}
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.comment.id }}/head"
      - name: Checkout repo 2
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.comment.node_id }}/head"
